config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # health check и PWA
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest


  # профили
  resources :profiles, only: [ :index, :show, :new, :create, :edit, :update ] do
    member do
      get :content
    end
  end

  # теги
  resources :tags, only: [ :index, :show ]

  # статьи
  resources :articles do
    collection do
      get :tagged
    end
  end

  # посты
  resources :posts do
    collection do
      get :feed
      get :popular
      get :search
    end

    # комменты
    resources :comments, only: [ :create, :edit, :update, :destroy ], shallow: true

    # лайки и закладки
    resources :likes, only: [ :create ], shallow: true
    resources :favorites, only: [ :create ], shallow: true

    # тонглы для лайков и закладок
    member do
      post :toggle_like
      post :toggle_bookmark
    end
  end

  # удаление лайков и закладок
  resources :likes, only: [ :destroy ]
  resources :favorites, only: [ :destroy ]

  # подписки
  resources :subscriptions, only: [ :create, :destroy ]

  # сообщения
  resources :messages, only: [ :index, :show, :create, :destroy ] do
    collection do
      get :sent
      get :inbox
    end
  end

  # админская часть
  namespace :admin do
    root to: "dashboard#index"
    resources :users
    resources :posts, except: [ :index, :show ] do
      resources :comments, only: [ :index, :destroy ]
    end
    resources :subscriptions, only: [ :index, :destroy ]
    resources :tags, only: [ :index, :create, :edit, :update, :destroy ]
    resources :application_forms, only: [ :index, :show, :destroy ]
  end

  get "about", to: "home#about"
  get "willbesoon", to: "home#willbesoon"
  get "signin", to: "home#signin"
  get "registration", to: "home#registration"
  get "feed", to: "home#feed"
  get "user", to: "home#user"

  # маршруты для авторизации через SessionsController
  get    "/signin",  to: "sessions#new"
  post   "/signin",  to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  match "/403", to: "errors#forbidden", via: :all
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_error", via: :all
  match "*path", to: "errors#not_found", via: :all

  root "home#about"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def willbesoon
  end

  def about
  end
end

app/views/home/about.html.erb
<%= stylesheet_link_tag "fonts", media: "all" %>
<%= stylesheet_link_tag "colors", media: "all" %>
<%= stylesheet_link_tag "about", media: "all" %>
<%= javascript_include_tag "animations", defer: true %>

<body>
    <!-- ХЕДЕР -->
    <header class="header">
        <div class="header_logo">FILMORA</div>

        <nav class="nav">
            <a href="/about">О нас</a>
            <a href="/feed">Лента</a>
            <a href="/subscription">Статьи Filmora</a>
        </nav>

        <div class="icons">
            <% if user_signed_in? %>
            <a href="/letterbox">
                <%= image_tag "letterbox.svg", class: "icon" %>
            </a>
            <% end %>
            <a href="/favorites">
            <%= image_tag "favorites.svg", class: "icon" %>
            </a>
            <a href="<%= user_signed_in? ? '/profile' : '/signin' %>">
            <%= image_tag "user.svg", class: "icon" %>
            </a>
        </div> 
    </header>

    <!-- ЗАГЛАВНАЯ -->
    <section class="main_block">
        <%= image_tag "rainbow_background.png", class: "background" %>
        <%= image_tag "filmora_main.svg", class: "filmora_main" %>
        <div class="main_text">Медиа-сервис для любителей<br>аналоговых технологий</div>
    </section>

    <!-- О НАС -->
    <section class="about">
        <div class="big">КТО&nbsp;МЫ?</div>
        <div class="small"> 
            Мы – Filmora, медиа-сервис для тех, кто любит аналоговые технологии. 
            Здесь нет гонки за&nbsp;идеалом — только <span class="underline">искренность</span> кадра 
            и&nbsp;тепло настоящего света. Мы верим, что аналоговая техника — <span class="underline">не&nbsp;прошлое, 
            а&nbsp;способ видеть мир осознанно</span>, с&nbsp;вниманием к&nbsp;деталям и&nbsp;уважением к&nbsp;ремеслу.
        </div>
        <%= image_tag "boy.png", class: "boy" %>
    </section>

    <!-- ЧТО МЫ ПРЕДЛАГАЕМ? -->
    <section class="what">
        <div class="big_what">ЧТО МЫ ПРЕДЛАГАЕМ?</div>

        <%= image_tag "polaroid.png", class: "polaroid" %>

        <div class="sections_tabs">
            <button class="section_tab active" data-tab="community">01</button>
            <button class="section_tab" data-tab="information">02</button>
            <button class="section_tab" data-tab="subscription">03</button>
            <button class="section_tab" data-tab="events">04</button>
        </div>

        <div class="sections_cards">
            <article class="section_card active" data-content="community">
                <h3 class="section_card_title">СООБЩЕСТВО</h3>
                <div class="section_card_text">
                    Давно мечтали найти себе друзей по&nbsp;интересу?<br>Тогда Filmora для вас.
                    Станьте частью нашего<br>сообщества: пишите и&nbsp;читайте посты,
                    <br>коммуницируйте с&nbsp;другими пользователями<br>и&nbsp;обменивайтесь опытом.
                </div>
            </article>

            <article class="section_card" data-content="information">
                <h3 class="section_card_title">ЗНАНИЯ</h3>
                <div class="section_card_text">
                    На нашем сервисе вы можете найти статьи<br>от&nbsp;экспертов Filmora и&nbsp;других 
                    пользователях<br>о&nbsp;пленочной фото и&nbsp;видео съемке, ремонте<br>и&nbsp;реставрации
                    техники и&nbsp;опыте<br>пользования аналоговой техникой.
                </div>
            </article>

            <article class="section_card" data-content="subscription">
                <h3 class="section_card_title">ПОДПИСКА</h3>
                <div class="section_card_text">
                    Подписка на винил и&nbsp;CD с&nbsp;ежемесячной<br>подборкой айтемов
                    от&nbsp;Filmora. Таким образом<br>вы не только получаете новый опыт и пополняете<br>коллекци,
                    но и поддерживаете редакцию.
                </div>
            </article>

            <article class="section_card" data-content="events">
                <h3 class="section_card_title">МЕРОПРИЯТИЯ</h3>
                <div class="section_card_text">
                    Вы можете посетить наши оффлайн и&nbsp;онлайн<br>мероприятия. Мы регулярно
                    проводим свопы,<br>мастер-классы по ремонту, а также маркеты.<br>Вы можете узнать о них из рассылки.
                </div>
            </article>
        
        </div>
    </section>

    <!-- РАССЫЛКА -->
    <section class="news">
        <%= image_tag "orange_background.png", class: "background_news" %>

        <div class="news_box">
            <div class="big_news">
                КАК НЕ ПРОПУСТИТЬ<br>НОВОСТИ FILMORA?
            </div>

            <div class="small_news">
                Просто подпишись на рассылку и первым<br>
                узнаешь о новых фишках Filmora.
            </div>

            <div class="wrapper">
                <label for="email">E-mail</label>
                <input
                    type="email"
                    id="email"
                    placeholder="Введите ваш e-mail"
                    class="box"
                >

                <div class="yesno">
                    <input
                        type="checkbox"
                        class="custom-checkbox"
                        id="agree"
                    >
                    <label for="agree" class="yesno_text">
                        Я согласен на получение<br>
                        рассылки от Filmora
                    </label>
                </div>

                <button class="button" disabled>
                    Подписаться на рассылку
                </button>
            </div>
        </div>
    </section>

    <script>
        const emailInput = document.querySelector('.box');
        const checkbox = document.querySelector('#agree');
        const button = document.querySelector('.button');

        // смена цвета текста email
        emailInput.addEventListener('input', () => {
            emailInput.classList.toggle('filled', emailInput.value.trim() !== '');
        });

        // включение / выключение кнопки по чекбоксу
        checkbox.addEventListener('change', () => {
            button.disabled = !checkbox.checked;
        });

        // клик по кнопке
        button.addEventListener('click', (e) => {
            e.preventDefault();

            button.textContent = 'Вы подписаны на рассылку';
            button.disabled = true;
            button.classList.add('subscribed');
        });
    </script>

    <!-- ФУТЕР -->
    <footer class="footer">
        <div class="footer_logo">
            FILMORA
        </div>
        
        <div class="footer_info">
        <div>
            <span class="label">
            <span class="grey_text">создательницы:</span><br>
            <span class="black_text">Александра Арефьева</span><br>
            <span class="black_text">Старовойтова Евгения</span>
        </div>

        <div>
            <span class="label">
            <span class="grey_text">кураторы:</span><br>
            <span class="black_text">Федор Ноздрин</span><br>
            <span class="black_text">Захар День</span>
        </div>
    </footer>
</body>

app/views/home/feed.html.erb
<%= stylesheet_link_tag "fonts", media: "all" %>
<%= stylesheet_link_tag "colors", media: "all" %>
<%= stylesheet_link_tag "feed", media: "all" %>
<%= javascript_include_tag "tabs", defer: true %>

<body>

    <!-- ХЕДЕР -->
    <header class="header">
    <div class="header_logo">
        FILMORA
    </div>

    <nav class="nav">
        <a href="/about">О нас</a>
        <a href="/feed">Лента</a>
        <a href="/subscription">Статьи Filmora</a>
    </nav>

    <div class="icons">
        <% if user_signed_in? %>
        <a href="/letterbox">
            <%= image_tag "letterbox.svg", class: "icon" %>
        </a>
        <% end %>
        <a href="/favorites">
        <%= image_tag "favorites.svg", class: "icon" %>
        </a>
        <a href="/signin">
        <%= image_tag "user.svg", class: "icon" %>
        </a>
    </div>
    </header>

    <!-- РАЗДЕЛЫ -->

    <section class="rasdeli">
        <div class="big">
            РАЗДЕЛЫ
        </div>

        <div class="sections_tabs">
            <button class="sections_tab active" data-tab="community">Сообщество</button>
            <button class="sections_tab" data-tab="subscription">Подписка</button>
            <button class="sections_tab" data-tab="events">События</button>
        </div>

        <div class="sections_cards">
            <!-- Сообщество -->
            <article class="section_card active" data-content="community">
                <h3 class="section_card_title">
                    КАКИЕ ОШИБКИ<br>ПРОЩАЕТ ПЛЕНКА
                </h3>
                <a href="#" class="section_card_link">Обсудить →</a>
            </article>

            <article class="section_card active" data-content="community">
                <h3 class="section_card_title">
                    АРХИВЫ,<br>КОТОРЫЕ НИКТО НЕ ПРОСИЛ СОЗДАВАТЬ
                </h3>
                <a href="#" class="section_card_link">Обсудить →</a>
            </article>

            <article class="section_card active" data-content="community">
                <h3 class="section_card_title">
                    ЗАЧЕМ МЫ ПРОДОЛЖАЕМ ЧИНИТЬ?
                </h3>
                <a href="#" class="section_card_link">Обсудить →</a>
            </article>

            <!-- Подписка -->
            <article class="section_card" data-content="subscription">
                <h3 class="section_card_title">CD ИЛИ ВИНИЛ?<br>КАК ВЫБРАТЬ ПОДПИСКУ</h3>
                <div class="data">Наша подписка может включать в себя как CD так и&nbsp;винил, но как понять, что подходит вам?</div>
                <a href="#" class="section_card_link">Подробнее →</a>
            </article>

            <article class="section_card" data-content="subscription">
                <h3 class="section_card_title">ПОДДЕРЖКА РАБОТЫ РЕДАКЦИИ FILMORA</h3>
                <div class="data">Подписка помогает проекту развиваться как независимому формату</div>
                <a href="#" class="section_card_link">Подробнее →</a>
            </article>

            <!-- События -->
            <article class="section_card" data-content="events">
                <h3 class="section_card_title">ЧИНИМ СТАРЫЕ<br>CD-ПЛЕЕРЫ<br>И ОЖИВЛЯЕМ КАССЕТНЫЕ ДЕКИ</h3>
                <div class="data">Через 2 дня</div>
                <a href="#" class="section_card_link">Участвовать →</a>
            </article>

            <article class="section_card" data-content="events">
                <h3 class="section_card_title">Разбираем ВАШИ старые кассеты<br>и&nbsp;личные архивы (АНОНИМНО)</h3>
                <div class="data">Через 5 дней</div>
                <a href="#" class="section_card_link">Участвовать →</a>
            </article>

            <article class="section_card" data-content="events">
                <h3 class="section_card_title">Разбираем домашние видеоархивы на&nbsp;MiniDV и VHS</h3>
                <div class="data">Через неделю</div>
                <a href="#" class="section_card_link">Участвовать →</a>
            </article>
    </section>

    <!--  СТАТЬИ -->


    <section class="articles">
    <div class="big">
        СТАТЬИ
    </div>

    <div class="articles_tags">
        <span class="articles_tag">Аналоговая техника</span>
        <span class="articles_tag">Ранняя цифра</span>
        <span class="articles_tag">Плёнка</span>
        <span class="articles_tag">Физические носители</span>
        <span class="articles_tag">Визуальный шум</span>
        <span class="articles_tag">Ремонт</span>
        <span class="articles_tag">Архивность</span>
        <span class="articles_tag">Медленные процессы</span>
    </div>

    <div class="articles_list">

        <article class="article_card_long">
        <div class="article_image"></div>

        <div class="article_content">
            <h3 class="article_title">
            ЗАЧЕМ МЫ ГОВОРИМ ПРО&nbsp;АНАЛОГОВУЮ<br>
            ТЕХНИКУ СЕГОДНЯ
            </h3>

            <p class="article_text">
            Интерес к&nbsp;старой технике сегодня растёт, но&nbsp;разговор о&nbsp;ней часто поверхностный.
            Обычно обсуждают эстетику или противопоставляют её современной цифре, почти не&nbsp;затрагивая
            сам процесс и&nbsp;повседневный опыт использования.
            </p>

            <a href="#" class="article_link">
            Читать полностью →
            </a>
        </div>
        </article>

        <article class="article_card_shorts">
        <div class="article_gallery">
            <div class="gallery_item"></div>
            <div class="gallery_item"></div>
            <div class="gallery_item"></div>
        </div>

        <div class="article_content">
            <h3 class="article_title">
            ПОЛГОДА С CANON POWERSHOT A95
            </h3>

            <p class="article_text">
            Пишу этот текст скорее как заметку для тех, кто думает брать старую компактную цифру, чем как полноценный обзор.
            Canon PowerShot A95 у&nbsp;меня появился случайно, нашёлся в&nbsp;коробке с&nbsp;техникой родственников
            и&nbsp;оказался в&nbsp;рабочем состоянии.
            </p>

            <a href="#" class="article_link">
            Читать полностью →
            </a>
        </div>
        </article>

        <article class="article_card_long">
        <div class="article_image"></div>

        <div class="article_content">
            <h3 class="article_title">
                ПЕРЕХОД НА АНАЛОГ:<br>Я УСТАЛ ОТ ТИКТОКА
            </h3>

            <p class="article_text">
                В&nbsp;последнее время все чаще замечаю за&nbsp;собой упадок интереса к&nbsp;коротким видео в&nbsp;интернете. При этом пересмотреть «Властелина колец» 
                не&nbsp;хватает терпения. Будь оно проклято это клиповое мышление! Я перехожу на аналог!
            </p>

            <a href="#" class="article_link">
            Читать полностью →
            </a>
        </div>
        </article>

    </div>
    </section>


    <!-- ФУТЕР -->
    <footer class="footer">
        <div class="footer_logo">
            FILMORA
        </div>
        
        <div class="footer_info">
        <div>
            <span class="label">
            <span class="grey_text">создательницы:</span><br>
            <span class="black_text">Александра Арефьева</span><br>
            <span class="black_text">Старовойтова Евгения</span>
        </div>

        <div>
            <span class="label">
            <span class="grey_text">кураторы:</span><br>
            <span class="black_text">Федор Ноздрин</span><br>
            <span class="black_text">Захар День</span>
        </div>
    </footer>

app/views/home/registration.html.erb
<%= stylesheet_link_tag "fonts", media: "all" %>
<%= stylesheet_link_tag "colors", media: "all" %>
<%= stylesheet_link_tag "signin", media: "all" %>
<%= javascript_include_tag "email_password_input", defer: true %>

<body>
    <!-- ХЕДЕР -->
    <header class="header">
        <div class="header_logo">FILMORA</div>

        <nav class="nav">
            <a href="/about">О нас</a>
            <a href="/feed">Лента</a>
            <a href="/subscription">Статьи Filmora</a>
        </nav>

        <div class="icons">
            <% if user_signed_in? %>
            <a href="/letterbox">
                <%= image_tag "letterbox.svg", class: "icon" %>
            </a>
            <% end %>
            <a href="/favorites">
            <%= image_tag "favorites.svg", class: "icon" %>
            </a>
            <a href="/signin">
            <%= image_tag "user.svg", class: "icon" %>
            </a>
        </div> 
    </header>

    <!-- ОСНОВНОЕ -->
    <main class="login_page">
        <div class="big">РЕГИСТРАЦИЯ</div>

        <div class="card-wrapper">
            <div class="card">
                <label for="card_text">E-mail</label>
                <input type="email" placeholder="Введите ваш e-mail" class="email_box">

                <label for="card_text">Пароль</label>
                <input type="password" placeholder="Придумайте пароль" class="password_box">

                <button class="button">Зарегистрироваться</button>
            </div>

            <div class="links">
                <a href="/signin">Уже есть аккаунт?</a>
            </div>
        </div>
    </main>

    <!-- ФУТЕР -->
    <footer class="footer">
        
        <div class="footer_info">
        <div>
            <span class="label">
            <span class="grey_text">создательницы:</span><br>
            <span class="black_text">Александра Арефьева</span><br>
            <span class="black_text">Старовойтова Евгения</span>
        </div>

        <div>
            <span class="label">
            <span class="grey_text">кураторы:</span><br>
            <span class="black_text">Федор Ноздрин</span><br>
            <span class="black_text">Захар День</span>
        </div>
        </div>
    </footer>

</body>

app/views/home/signin.html.erb
<%= stylesheet_link_tag "fonts", media: "all" %>
<%= stylesheet_link_tag "colors", media: "all" %>
<%= stylesheet_link_tag "signin", media: "all" %>
<%= javascript_include_tag "email_password_input", defer: true %>

<body>
    <!-- ХЕДЕР -->
    <header class="header">
        <div class="header_logo">FILMORA</div>

        <nav class="nav">
            <a href="/about">О нас</a>
            <a href="/feed">Лента</a>
            <a href="/subscription">Статьи Filmora</a>
        </nav>

        <div class="icons">
            <% if user_signed_in? %>
            <a href="/letterbox">
                <%= image_tag "letterbox.svg", class: "icon" %>
            </a>
            <% end %>
            <a href="/favorites">
            <%= image_tag "favorites.svg", class: "icon" %>
            </a>
            <a href="/signin">
            <%= image_tag "user.svg", class: "icon" %>
            </a>
        </div> 
    </header>

    <!-- ОСНОВНОЕ -->
    <main class="login_page">
        <div class="big">ВХОД</div>

        <div class="card-wrapper">
            <%= form_with url: signin_path, method: :post, html: { class: "card" } do |f| %>
                <label for="email_box">E-mail</label>
                <%= f.email_field :email, placeholder: "Введите ваш e-mail", class: "email_box", id: "email_box" %>

                <label for="password_box">Пароль</label>
                <%= f.password_field :password, placeholder: "Введите ваш пароль", class: "password_box", id: "password_box" %>

                <%= f.submit "Войти", class: "button" %>
            <% end %>

            <div class="links">
                <a href="/forbid_password">Забыли пароль?</a>
                <a href="/registration">Зарегистрироваться</a>
            </div>
        </div>
    </main>

    <!-- ФУТЕР -->
    <footer class="footer">
        
        <div class="footer_info">
        <div>
            <span class="label">
            <span class="grey_text">создательницы:</span><br>
            <span class="black_text">Александра Арефьева</span><br>
            <span class="black_text">Старовойтова Евгения</span>
        </div>

        <div>
            <span class="label">
            <span class="grey_text">кураторы:</span><br>
            <span class="black_text">Федор Ноздрин</span><br>
            <span class="black_text">Захар День</span>
        </div>
        </div>
    </footer>

</body>

app/views/home/user.html.erb
<%= stylesheet_link_tag "fonts", media: "all" %>
<%= stylesheet_link_tag "colors", media: "all" %>
<%= stylesheet_link_tag "user", media: "all" %>

<body>
    
    <!-- ХЕДЕР -->
    <header class="header">
        <div class="header_logo">FILMORA</div>

        <nav class="nav">
            <a href="/about">О нас</a>
            <a href="/feed">Лента</a>
            <a href="/subscription">Статьи Filmora</a>
        </nav>

        <div class="icons">
            <% if user_signed_in? %>
            <a href="/letterbox">
                <%= image_tag "letterbox.svg", class: "icon" %>
            </a>
            <% end %>
            <a href="/favorites">
            <%= image_tag "favorites.svg", class: "icon" %>
            </a>
            <a href="/signin">
            <%= image_tag "user.svg", class: "icon" %>
            </a>
        </div> 
    </header>

    <!-- НАСТРОЙКИ -->
    <a href="#">
        <%= image_tag "grainshift.svg", class: "grainshift" %>
    </a>

    <!-- ОБСУЖДЕНИЯ -->   
    <div class="big">ОБСУЖДЕНИЯ</div>

    <div class="discussion">
        <div class="discussion_wrapper">
            <div class="title">ЗАЧЕМ МЫ ПРОДОЛЖАЕМ ЧИНИТЬ?</div>
            <div class="new_comments">5 новых комментариев</div>
        </div>
        <div class="text">
            Мне кажется, тут дело не столько в экономике или экологии, сколько в ощущении контроля. Когда чинишь вещь, ты понимаешь, из чего ...
        </div>
        <a href="#", class="discussion_link">Продолжить обсуждение →</a>
    </div>
    
    <div class="discussion">
        <div class="discussion_wrapper">
            <div class="title">ПЕРЕХОД НА АНАЛОГ: Я УСТАЛ ОТ ТИКТОКА?</div>
            <div class="new_comments">12 новых комментариев</div>
        </div>
        <div class="text">
            Вы че, «Властелин колец» вообще не длинный. А вообще тик ток разжижает мозг, доказанный факт.
        </div>
        <a href="#", class="discussion_link">Продолжить обсуждение →</a>
    </div>

    <!-- МОИ СТАТЬИ -->
    <div class="article_wrapper">
        <div class="big">МОИ СТАТЬИ</div>
        <button class="new_article">
            Опубликовать статью
        </button>
    </div>

    <div class="article">
        <div class="title">ПОЛГОДА С CANON POWERSHOT A95</div>

        <div class="text">
            Пишу этот текст скорее как заметку для тех, кто думает брать старую компактную цифру, чем как полноценный обзор.
            Canon PowerShot A95 у&nbsp;меня появился случайно, нашёлся в&nbsp;коробке с&nbsp;техникой родственников
            и&nbsp;оказался в&nbsp;рабочем состоянии.
        </div>

        <div class="results">
            <div class="result">
                <%= image_tag "likes_icon.svg", class: "icon" %>
                <div class="count">0</div>
            </div>
            <div class="result">
                <%= image_tag "comments_icon.svg", class: "icon" %>
                <div class="count">0</div>
            </div>
            <div class="result">
                <%= image_tag "favs_icon.svg", class: "icon" %>
                <div class="count">0</div>
            </div>
        </div>
    </div>

    <!-- ФУТЕР -->
    <footer class="footer">
        <div class="footer_logo">
            FILMORA
        </div>
        
        <div class="footer_info">
        <div>
            <span class="label">
            <span class="grey_text">создательницы:</span><br>
            <span class="black_text">Александра Арефьева</span><br>
            <span class="black_text">Старовойтова Евгения</span>
        </div>

        <div>
            <span class="label">
            <span class="grey_text">кураторы:</span><br>
            <span class="black_text">Федор Ноздрин</span><br>
            <span class="black_text">Захар День</span>
        </div>
    </footer>

</body>